const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="samsamsun789@gmail.com"
global.location="Lahore,Pakistan."
global.mongodb= process.env.MONGODB_URI || ""
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "120363023983262391@g.us"
global.DATABASE_URI = process.env.DATABASE_URL || ""

global.timezone= process.env.TZ || process.env.TIME_ZONE || "Asia/Karachi";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://telegra.ph/file/d5b1c3544fedc23e11a06.jpg" ; // SET LOGO FOR IMAGE 



global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "null";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "923184474176";




//========================= [ BOT SETTINGS ] =========================\\
global.style = process.env.STYLE   || '5',  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || "true";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 3,
global.disablepm = process.env.DISABLE_PM || "false",
global.MsgsInLog = process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES|| "text",
global.waPresence= process.env.WAPRESENCE ||  "set according to your need" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "923184474176,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd-1.vercel.app"
global.scan = "https://suhail-md-vtsf.onrender.com/";

module.exports = {

  menu: process.env.MENU || "", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || ".",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "V.1.2.8",
  caption : process.env.CAPTION || "©sᴜʜᴀɪʟ²²¹-ᴍᴅ" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Suhail-MD",
  packname: process.env.PACK_NAME || "❤️‍🔥",
  botname : process.env.BOT_NAME  || "sᴜʜᴀɪʟ-ᴍᴅ",
  ownername:process.env.OWNER_NAME|| "𝐀𝐜𝐡𝐮-𝐱𝐝",

  sessionName:process.env.SESSION_ID || "SUHAIL_12_48_10_10_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMCxcbiAgICAgICAgMTYzLFxuICAgICAgICAxMjQsXG4gICAgICAgIDUwLFxuICAgICAgICAxMTAsXG4gICAgICAgIDE2LFxuICAgICAgICAyOCxcbiAgICAgICAgMjMzLFxuICAgICAgICAzOCxcbiAgICAgICAgMTkxLFxuICAgICAgICAzNyxcbiAgICAgICAgMTI0LFxuICAgICAgICA0NCxcbiAgICAgICAgMTk2LFxuICAgICAgICAyMTAsXG4gICAgICAgIDcxLFxuICAgICAgICAxOTIsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTkxLFxuICAgICAgICAyNDksXG4gICAgICAgIDExOCxcbiAgICAgICAgMTM2LFxuICAgICAgICAxOTYsXG4gICAgICAgIDEwMCxcbiAgICAgICAgNSxcbiAgICAgICAgMTMsXG4gICAgICAgIDEwLFxuICAgICAgICAyNCxcbiAgICAgICAgOCxcbiAgICAgICAgNjAsXG4gICAgICAgIDUxLFxuICAgICAgICA5NVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICA0MixcbiAgICAgICAgMTEsXG4gICAgICAgIDE0MixcbiAgICAgICAgMjM2LFxuICAgICAgICAyMDEsXG4gICAgICAgIDMwLFxuICAgICAgICAzMSxcbiAgICAgICAgMTYsXG4gICAgICAgIDI0NixcbiAgICAgICAgOTcsXG4gICAgICAgIDk1LFxuICAgICAgICA3OCxcbiAgICAgICAgMTgzLFxuICAgICAgICAxNTIsXG4gICAgICAgIDM1LFxuICAgICAgICAxMixcbiAgICAgICAgNTksXG4gICAgICAgIDY0LFxuICAgICAgICA5MixcbiAgICAgICAgMTg4LFxuICAgICAgICA2OCxcbiAgICAgICAgMjQyLFxuICAgICAgICA4MixcbiAgICAgICAgMTY3LFxuICAgICAgICA4MyxcbiAgICAgICAgMTI0LFxuICAgICAgICAyNDUsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMjUsXG4gICAgICAgIDI3LFxuICAgICAgICAyNTUsXG4gICAgICAgIDc0XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyXCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNTIsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTMwLFxuICAgICAgICAzOSxcbiAgICAgICAgMjcsXG4gICAgICAgIDcxLFxuICAgICAgICAxNjYsXG4gICAgICAgIDI0LFxuICAgICAgICAxODAsXG4gICAgICAgIDEsXG4gICAgICAgIDM5LFxuICAgICAgICA2OSxcbiAgICAgICAgMTQ0LFxuICAgICAgICAyNixcbiAgICAgICAgMTgzLFxuICAgICAgICA0MSxcbiAgICAgICAgMjI2LFxuICAgICAgICA1OCxcbiAgICAgICAgOSxcbiAgICAgICAgMjgsXG4gICAgICAgIDc5LFxuICAgICAgICAyNTIsXG4gICAgICAgIDUsXG4gICAgICAgIDgsXG4gICAgICAgIDE0NyxcbiAgICAgICAgMjA5LFxuICAgICAgICA3MSxcbiAgICAgICAgNDEsXG4gICAgICAgIDExMixcbiAgICAgICAgMTEyLFxuICAgICAgICAxMDcsXG4gICAgICAgIDk5XG4gICAgICBdXG4gICAgfSxcbiAgICBcInB1YmxpY1wiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1MCxcbiAgICAgICAgMTE2LFxuICAgICAgICAyMjEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTksXG4gICAgICAgIDE4NixcbiAgICAgICAgMTgxLFxuICAgICAgICAxMzMsXG4gICAgICAgIDExMixcbiAgICAgICAgOTAsXG4gICAgICAgIDE4OSxcbiAgICAgICAgODMsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMjcsXG4gICAgICAgIDExOCxcbiAgICAgICAgMjMsXG4gICAgICAgIDE5OSxcbiAgICAgICAgMTM5LFxuICAgICAgICAxNTUsXG4gICAgICAgIDI4LFxuICAgICAgICA0NyxcbiAgICAgICAgMTMsXG4gICAgICAgIDk0LFxuICAgICAgICAyMDcsXG4gICAgICAgIDM3LFxuICAgICAgICA1NyxcbiAgICAgICAgODMsXG4gICAgICAgIDgwLFxuICAgICAgICA3NCxcbiAgICAgICAgNyxcbiAgICAgICAgMzMsXG4gICAgICAgIDc1XG4gICAgICBdXG4gICAgfVxuICB9LFxuICBcInNpZ25lZElkZW50aXR5S2V5XCI6IHtcbiAgICBcInByaXZhdGVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMDQsXG4gICAgICAgIDY1LFxuICAgICAgICAyMzksXG4gICAgICAgIDQsXG4gICAgICAgIDIzNSxcbiAgICAgICAgMTAxLFxuICAgICAgICAxNzcsXG4gICAgICAgIDcsXG4gICAgICAgIDczLFxuICAgICAgICAxMjQsXG4gICAgICAgIDkyLFxuICAgICAgICAyMDIsXG4gICAgICAgIDYxLFxuICAgICAgICA5MixcbiAgICAgICAgMjQ0LFxuICAgICAgICAxOTAsXG4gICAgICAgIDE1NCxcbiAgICAgICAgOTIsXG4gICAgICAgIDE4OCxcbiAgICAgICAgMjA2LFxuICAgICAgICA4MyxcbiAgICAgICAgMTE4LFxuICAgICAgICAxOTQsXG4gICAgICAgIDExNCxcbiAgICAgICAgMjI2LFxuICAgICAgICA5NCxcbiAgICAgICAgMjM0LFxuICAgICAgICAyMjgsXG4gICAgICAgIDIxOCxcbiAgICAgICAgNTYsXG4gICAgICAgIDc0LFxuICAgICAgICAxMDNcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNDMsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTcsXG4gICAgICAgIDQ2LFxuICAgICAgICA4MCxcbiAgICAgICAgMTM0LFxuICAgICAgICAxOTQsXG4gICAgICAgIDE5MyxcbiAgICAgICAgNixcbiAgICAgICAgMTE5LFxuICAgICAgICAxNDYsXG4gICAgICAgIDIzMCxcbiAgICAgICAgMjI3LFxuICAgICAgICAxNTIsXG4gICAgICAgIDE2NSxcbiAgICAgICAgMjMyLFxuICAgICAgICAyNDgsXG4gICAgICAgIDI3LFxuICAgICAgICAyMjcsXG4gICAgICAgIDExOSxcbiAgICAgICAgMjM3LFxuICAgICAgICAxOTksXG4gICAgICAgIDE4NixcbiAgICAgICAgMTg0LFxuICAgICAgICAxNzcsXG4gICAgICAgIDIzNixcbiAgICAgICAgMCxcbiAgICAgICAgMTk1LFxuICAgICAgICAyMDUsXG4gICAgICAgIDIxMCxcbiAgICAgICAgMjE3LFxuICAgICAgICAxMlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAyMDgsXG4gICAgICAgICAgNzQsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDEsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDE4NyxcbiAgICAgICAgICAxOTksXG4gICAgICAgICAgMTEsXG4gICAgICAgICAgNyxcbiAgICAgICAgICAxMDYsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMjUzLFxuICAgICAgICAgIDIxMSxcbiAgICAgICAgICAyMzcsXG4gICAgICAgICAgMTgzLFxuICAgICAgICAgIDI1MCxcbiAgICAgICAgICAxNjAsXG4gICAgICAgICAgMjQ5LFxuICAgICAgICAgIDIzNixcbiAgICAgICAgICA5NSxcbiAgICAgICAgICA2MCxcbiAgICAgICAgICAyMzgsXG4gICAgICAgICAgMTQwLFxuICAgICAgICAgIDUwLFxuICAgICAgICAgIDE3NixcbiAgICAgICAgICAyMzQsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDY2LFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDg3XG4gICAgICAgIF1cbiAgICAgIH0sXG4gICAgICBcInB1YmxpY1wiOiB7XG4gICAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgICBcImRhdGFcIjogW1xuICAgICAgICAgIDIzLFxuICAgICAgICAgIDk0LFxuICAgICAgICAgIDE3NyxcbiAgICAgICAgICA4MSxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICA3OCxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA5OSxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICA2OCxcbiAgICAgICAgICAxODUsXG4gICAgICAgICAgMTgyLFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICA2MyxcbiAgICAgICAgICA1MyxcbiAgICAgICAgICAyMjQsXG4gICAgICAgICAgMjQ1LFxuICAgICAgICAgIDczLFxuICAgICAgICAgIDc3LFxuICAgICAgICAgIDIxMyxcbiAgICAgICAgICAzNyxcbiAgICAgICAgICAxMjQsXG4gICAgICAgICAgNjQsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxNjUsXG4gICAgICAgICAgMTYsXG4gICAgICAgICAgMTk2LFxuICAgICAgICAgIDIwNCxcbiAgICAgICAgICA2NixcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgNTdcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH0sXG4gICAgXCJzaWduYXR1cmVcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxMjMsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTU4LFxuICAgICAgICAxOSxcbiAgICAgICAgOTEsXG4gICAgICAgIDc0LFxuICAgICAgICAyMjIsXG4gICAgICAgIDE5NyxcbiAgICAgICAgMTI1LFxuICAgICAgICAxMDksXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTI0LFxuICAgICAgICAyNDcsXG4gICAgICAgIDEwNSxcbiAgICAgICAgMjAsXG4gICAgICAgIDI1MSxcbiAgICAgICAgMzMsXG4gICAgICAgIDIzOSxcbiAgICAgICAgMTIwLFxuICAgICAgICAyNTIsXG4gICAgICAgIDE0NSxcbiAgICAgICAgMjIxLFxuICAgICAgICA4OCxcbiAgICAgICAgMjksXG4gICAgICAgIDIyOCxcbiAgICAgICAgMTA5LFxuICAgICAgICA5MSxcbiAgICAgICAgMTMwLFxuICAgICAgICA0MixcbiAgICAgICAgMjAsXG4gICAgICAgIDIwLFxuICAgICAgICAxNTUsXG4gICAgICAgIDIyMCxcbiAgICAgICAgMTE3LFxuICAgICAgICAyNDUsXG4gICAgICAgIDI1MCxcbiAgICAgICAgMTI5LFxuICAgICAgICA1LFxuICAgICAgICAyMjksXG4gICAgICAgIDE1NixcbiAgICAgICAgMyxcbiAgICAgICAgOTEsXG4gICAgICAgIDM5LFxuICAgICAgICA0OCxcbiAgICAgICAgMTAwLFxuICAgICAgICA1NSxcbiAgICAgICAgNTksXG4gICAgICAgIDIwNixcbiAgICAgICAgNTcsXG4gICAgICAgIDUyLFxuICAgICAgICAxMjksXG4gICAgICAgIDE1MSxcbiAgICAgICAgMjUsXG4gICAgICAgIDI0MixcbiAgICAgICAgNyxcbiAgICAgICAgMjI2LFxuICAgICAgICA4NSxcbiAgICAgICAgODksXG4gICAgICAgIDIzOSxcbiAgICAgICAgOTEsXG4gICAgICAgIDExMSxcbiAgICAgICAgMTUwLFxuICAgICAgICAyMjIsXG4gICAgICAgIDEzN1xuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMTIwLFxuICBcImFkdlNlY3JldEtleVwiOiBcIlNvRlhXVmt3b1k1VTU2UkhUaURzc2dPK2JRZlUvd3N6cGJXSW55Z0ZVQkU9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtcbiAgICB7XG4gICAgICBcImtleVwiOiB7XG4gICAgICAgIFwicmVtb3RlSmlkXCI6IFwiOTE5NzQ2Mzc0OTM2QHMud2hhdHNhcHAubmV0XCIsXG4gICAgICAgIFwiZnJvbU1lXCI6IHRydWUsXG4gICAgICAgIFwiaWRcIjogXCI0QTc4RkNFQTBGOURGNDRDQ0I4QUVBMEU1NDFDQjcxOFwiXG4gICAgICB9LFxuICAgICAgXCJtZXNzYWdlVGltZXN0YW1wXCI6IDE3Mjg1NjQ1MjNcbiAgICB9LFxuICAgIHtcbiAgICAgIFwia2V5XCI6IHtcbiAgICAgICAgXCJyZW1vdGVKaWRcIjogXCI5MTk3NDYzNzQ5MzZAcy53aGF0c2FwcC5uZXRcIixcbiAgICAgICAgXCJmcm9tTWVcIjogdHJ1ZSxcbiAgICAgICAgXCJpZFwiOiBcIjFFOUFEMTAxNEMwQzYwQUZGRkE5MTA1RjhBNEJBRjA3XCJcbiAgICAgIH0sXG4gICAgICBcIm1lc3NhZ2VUaW1lc3RhbXBcIjogMTcyODU2NDUyNFxuICAgIH1cbiAgXSxcbiAgXCJuZXh0UHJlS2V5SWRcIjogMzEsXG4gIFwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWRcIjogMzEsXG4gIFwiYWNjb3VudFN5bmNDb3VudGVyXCI6IDEsXG4gIFwiYWNjb3VudFNldHRpbmdzXCI6IHtcbiAgICBcInVuYXJjaGl2ZUNoYXRzXCI6IGZhbHNlXG4gIH0sXG4gIFwiZGV2aWNlSWRcIjogXCJaWVBpMXdFM1R3MnZ4enhUV0JSY1RRXCIsXG4gIFwicGhvbmVJZFwiOiBcImFiMjExNTdhLWY4N2YtNGM2Yi1iODU0LWY3N2M1NWI0YTYxN1wiLFxuICBcImlkZW50aXR5SWRcIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA1MCxcbiAgICAgIDE2OSxcbiAgICAgIDk1LFxuICAgICAgMTIyLFxuICAgICAgMTA1LFxuICAgICAgNTEsXG4gICAgICA0OSxcbiAgICAgIDc5LFxuICAgICAgMTMxLFxuICAgICAgMjQ5LFxuICAgICAgNzMsXG4gICAgICAxMDEsXG4gICAgICAxNDAsXG4gICAgICAxNzQsXG4gICAgICAzLFxuICAgICAgMixcbiAgICAgIDk5LFxuICAgICAgMTk5LFxuICAgICAgNzMsXG4gICAgICAzXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogdHJ1ZSxcbiAgXCJiYWNrdXBUb2tlblwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDExNCxcbiAgICAgIDIsXG4gICAgICAxMjksXG4gICAgICAxNCxcbiAgICAgIDExOSxcbiAgICAgIDE3NCxcbiAgICAgIDk1LFxuICAgICAgMTcxLFxuICAgICAgNjIsXG4gICAgICAxNTUsXG4gICAgICAxNTgsXG4gICAgICAxMTksXG4gICAgICAyNDIsXG4gICAgICAxOTQsXG4gICAgICAxOTEsXG4gICAgICAyMzksXG4gICAgICA0LFxuICAgICAgMTQ3LFxuICAgICAgMzgsXG4gICAgICAyMDlcbiAgICBdXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uXCI6IHt9LFxuICBcInBhaXJpbmdDb2RlXCI6IFwiN0dQWUZCMjZcIixcbiAgXCJtZVwiOiB7XG4gICAgXCJpZFwiOiBcIjkxOTc0NjM3NDkzNjozOEBzLndoYXRzYXBwLm5ldFwiLFxuICAgIFwibGlkXCI6IFwiODY3OTMyMDI0NDYzNjI6MzhAbGlkXCJcbiAgfSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDSWJHNS80RUVLV2FuN2dHR0FFZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJZRTkwdXJCRlNET2xabDJwdU5tVFF5UTlKOUhkeUJnaGFDNWp0c3pKa0NvPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcInZGNEtHbmpKRGM1aktyZ1hLVDFadXJ0dW5Kd2sxV05xd1p3MkJ1VEJhTENOTmd5bkpiLzFmeGxSRFBEcS93ZzI4MHEyL2hrNUFqUU5CTERxdEs5QkJBPT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIjBreEN0VnducnhJZm9RWGoydFBBbnQ2Y1h5Zk5yL0xTVjMzWkFDZUZmaEhrQndnZnJTdkszdmZFRUEvK1JUYTQ3Q0JLOTRYNjZDRkswSitXbjJkWGlRPT1cIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjkxOTc0NjM3NDkzNjozOEBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDc5LFxuICAgICAgICAgIDExNixcbiAgICAgICAgICAxODYsXG4gICAgICAgICAgMTc2LFxuICAgICAgICAgIDY5LFxuICAgICAgICAgIDcyLFxuICAgICAgICAgIDUxLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxMDIsXG4gICAgICAgICAgOTMsXG4gICAgICAgICAgMTY5LFxuICAgICAgICAgIDE4NCxcbiAgICAgICAgICAyMTcsXG4gICAgICAgICAgMTQ3LFxuICAgICAgICAgIDY3LFxuICAgICAgICAgIDM2LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDM5LFxuICAgICAgICAgIDIwOSxcbiAgICAgICAgICAyMjEsXG4gICAgICAgICAgMjAwLFxuICAgICAgICAgIDI0LFxuICAgICAgICAgIDMzLFxuICAgICAgICAgIDEwNCxcbiAgICAgICAgICA0NixcbiAgICAgICAgICA5OSxcbiAgICAgICAgICAxODIsXG4gICAgICAgICAgMjA0LFxuICAgICAgICAgIDIwMSxcbiAgICAgICAgICAxNDQsXG4gICAgICAgICAgNDJcbiAgICAgICAgXVxuICAgICAgfVxuICAgIH1cbiAgXSxcbiAgXCJwbGF0Zm9ybVwiOiBcImFuZHJvaWRcIixcbiAgXCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXBcIjogMTcyODU2NDUyMCxcbiAgXCJteUFwcFN0YXRlS2V5SWRcIjogXCJBQUFBQU82YVwiXG59IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBTzZhLmpzb24iOiAie1wia2V5RGF0YVwiOlwiYXJlUmx0M2NHZUFJelM1SEhXTlFpSFR1cmYyajhLSG0vMXR4eWxBYnJsND1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMzM5Njc5NDk0LFwiY3VycmVudEluZGV4XCI6MSxcImRldmljZUluZGV4ZXNcIjpbMCwxXX0sXCJ0aW1lc3RhbXBcIjpcIjE3Mjg1NjQ1MjY0OTdcIn0iCn0=",  // PUT SESSION ID HERE 
  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,

  aitts_Voice_Id : process.env.AITTS_ID || "37",
  ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY || "",
  WORKTYPE: process.env.WORKTYPE||process.env.MODE || "private",
  LANG: process.env.THEME ? process.env.THEME.toUpperCase() : "SUHAIL",



};




























global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
 
